import Image from "next/image";
import {Camera, ChartPie, Target, ArrowUpRight} from "lucide-react";
import Footer from "../components/Footer";
import InterestForm from "../components/InterestForm";
export default function Home(){return <><main>
<section className="hero wrap"><div><span className="eyebrow">AI FOOD & CALORIE TRACKING · IN TESTING</span><h1>Good food.<br/><span>Clearer choices.</span></h1><p className="lead">Turn a meal photo into calorie and macro estimates. Track your day and build habits that fit your life.</p><div className="actions"><a className="button" href="#early-access">Get early access <ArrowUpRight size={18}/></a><a className="text-link" href="#how-it-works">See how it works →</a></div><p className="muted">AI estimates are approximate. Review portions before logging.</p></div><div className="hero-visual"><span className="visual-label">MEET YOUR EVERYDAY FOOD DIARY</span><Image src="/images/carousel.png" alt="Alviva mobile app preview" width={850} height={950} priority className="app-preview"/><Image src="/images/chicken-bowl.webp" alt="Grilled chicken, rice and vegetables" width={240} height={160} className="hero-food"/><span className="testing-pill">● Currently in testing</span></div></section>
<div className="benefit-strip"><span><Camera/>Photo estimates</span><span><ChartPie/>Calories & macros</span><span><Target/>Daily goals</span></div>
<section id="features" className="wrap section"><span className="eyebrow">LESS GUESSWORK. MORE AWARENESS.</span><h2>A little clarity with every meal.</h2><div className="cards">{[{Icon:Camera,title:"Snap. Review. Log.",text:"Take a food photo to get an AI estimate of calories and macronutrients."},{Icon:ChartPie,title:"See your daily nutrition",text:"Keep your logged meals and nutrition totals in one place."},{Icon:Target,title:"Keep your goals in view",text:"Set your daily calorie goal and follow your food diary over time."}].map(({Icon,title,text})=><article className="card" key={title}><div className="icon"><Icon size={28}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="wrap section everyday"><Image src="/images/everyday-meals.webp" alt="Home-cooked daal, roti, salad and chicken rice" width={1536} height={1024} sizes="(max-width: 760px) 100vw, 50vw" className="everyday-photo"/><div><span className="eyebrow">FAMILIAR FOOD. A FRESH PERSPECTIVE.</span><h2>Built for your<br/>everyday meals.</h2><p className="lead">From home-cooked favourites to meals on the go, keep your food diary in one place.</p><p>Review your meal estimates and follow your daily nutrition goals.</p></div></section>
<section id="how-it-works" className="wrap section steps-section"><div><span className="eyebrow">A SIMPLE DAILY ROUTINE</span><h2>From first snap<br/>to daily habit.</h2><p className="lead">A food diary that starts with your camera.</p></div><ol className="steps">{[["Take a photo","Capture your meal in good lighting."],["Review the estimate","Check the suggested foods and portions before you log."],["Follow your day","See your logged meals alongside your daily goal."]].map(([title,text],i)=><li key={title}><span className="number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
<section className="wrap section affiliate-banner"><div><span className="eyebrow">FOR CREATORS & COMMUNITIES</span><h2>Help shape what comes next.</h2><p>Interested in sharing Alviva with your audience? Explore our planned affiliate program.</p></div><a className="button" href="/affiliate">Explore affiliate opportunities ↗</a></section>
<section id="faq" className="wrap section faq"><h2>A few things to know.</h2>{[["Is Alviva available to download?","Alviva is currently in testing. Request early access to ask about testing and launch updates."],["Are calorie estimates exact?","No. AI estimates are approximate and can vary with ingredients and portion size. Review your meal before logging."],["Is the affiliate program open?","We are collecting interest while the app is in testing. Commission rates, tracking and payouts have not been announced."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
<section id="early-access" className="wrap access section"><div><span className="eyebrow">JOIN THE TESTING JOURNEY</span><h2>Your next habit starts with one meal.</h2><p>Alviva is currently in testing. Request early access and launch updates.</p></div><InterestForm/></section>
</main><Footer/></>}
